create table public.delivery_persons (
  id bigint generated by default as identity not null,
  user_id bigint null,
  vehicle_type text null,
  vehicle_plate text null,
  is_available boolean null default true,
  current_location geometry null,
  rating numeric null default 5.0,
  range numeric(10,2) null default 10.0,
  created_at timestamp with time zone not null default timezone ('utc'::text, now()),
  updated_at timestamp with time zone not null default timezone ('utc'::text, now()),
  constraint delivery_persons_pkey primary key (id),
  constraint delivery_persons_user_id_fkey foreign KEY (user_id) references users (id) on delete CASCADE
) TABLESPACE pg_default;