create table public.delivery_requests (
  id bigint generated by default as identity not null,
  passenger_id bigint null,
  delivery_person_id bigint null,
  category text not null,
  description text null,
  pickup_notes text null,
  dropoff_notes text null,
  delivery_location geography null,
  pickup_location geography null,
  status text null default 'pending'::text,
  price numeric null,
  distance_km numeric null,
  created_at timestamp with time zone not null default timezone ('utc'::text, now()),
  updated_at timestamp with time zone not null default timezone ('utc'::text, now()),
  constraint delivery_requests_pkey primary key (id),
  constraint delivery_requests_delivery_person_id_fkey foreign KEY (delivery_person_id) references delivery_persons (id),
  constraint delivery_requests_passenger_id_fkey foreign KEY (passenger_id) references passengers (id) on delete CASCADE
) TABLESPACE pg_default;

create index IF not exists delivery_requests_delivery_location_idx on public.delivery_requests using gist (delivery_location) TABLESPACE pg_default;