import 'package:flutter/foundation.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import 'package:drivio_app/common/services/auth_service.dart';

/// Centralized service for user-submitted bug reports & feedback.
///
/// Stores data in the `bug_reports` table in Supabase.
///
/// Recommended Supabase table definition:
/// ```sql
/// create table public.bug_reports (
///   id bigint generated by default as identity primary key,
///   created_at timestamptz default now() not null,
///   user_id uuid, -- auth.users.id
///   internal_user_id bigint, -- public.users.id
///   role text,
///   platform text,
///   app_version text,
///   os text,
///   screen text,
///   severity text, -- 'low' | 'medium' | 'high'
///   type text,     -- 'bug' | 'idea' | 'other'
///   title text not null,
///   description text not null,
///   extra_context jsonb
/// );
/// ```
class FeedbackService {
  static final SupabaseClient _supabase = Supabase.instance.client;

  /// Submit a user-facing bug/feedback report.
  static Future<void> submitReport({
    required String title,
    required String description,
    String? screen,
    String? severity, // low | medium | high
    String? type, // bug | idea | other
    Map<String, dynamic>? extraContext,
  }) async {
    try {
      final authUser = _supabase.auth.currentUser;
      final role = await AuthService.getUserRole();
      final internalUserId = await AuthService.getInternalUserId();

      final payload = <String, dynamic>{
        'title': title,
        'description': description,
        'screen': screen,
        'severity': severity,
        'type': type,
        'user_id': authUser?.id,
        'internal_user_id': internalUserId,
        'role': role,
        'platform': kIsWeb ? 'web' : 'mobile',
        'os': defaultTargetPlatform.name,
        'app_version': extraContext != null ? extraContext['app_version'] : null,
        'extra_context': extraContext,
      };

      await _supabase.from('bug_reports').insert(payload);
    } catch (e) {
      debugPrint('❌ Failed to submit bug report: $e');
      rethrow;
    }
  }

  /// Convenience helper to submit an automatic error/crash report.
  static Future<void> submitErrorReport({
    required Object error,
    StackTrace? stackTrace,
    String? screen,
    Map<String, dynamic>? extraContext,
  }) async {
    final mergedContext = {
      'stackTrace': stackTrace.toString(),
      'error_type': error.runtimeType.toString(),
      ...?extraContext,
    };

    await submitReport(
      title: 'Automatic error: ${error.runtimeType}',
      description: error.toString(),
      screen: screen,
      type: 'bug',
      severity: 'high',
      extraContext: mergedContext,
    );
  }
}

